import type { Metadata } from "next";
import { Titillium_Web } from "next/font/google";
import "./globals.css";
import ClientComponent from "./clienteComponent";
import Navbar from "./components/navbar";
import Footer from "./components/footer";

const titillium = Titillium_Web({
  weight: "400",
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Anywhere Talent",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={titillium.className}
      >
        <ClientComponent />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
